import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "The Blog - Este é um blog com next.js",
  description: "Generated by create next app",
};


type RootLayoutProps = {
  children: React.ReactNode;
}


export default function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body>
        <header><h1>Header</h1></header>
        <div className="bg-red-400">{children}</div>
        <footer><h1>footer</h1></footer>
      </body>
    </html>
  );
}
